"""empty message

Revision ID: 73312326b620
Revises: 8bc8a22909c4
Create Date: 2021-05-13 21:30:36.158899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73312326b620'
down_revision = '8bc8a22909c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
